### ISSUE TITLE
competition_list_files returns empty file list

### ISSUE THREAD

**Issue by deepakn97** [Kaggle/kaggle-api#616] opened 2024-07-30 14:52 UTC
Hi, 

I am trying to list competition data files using the Kaggle Python API. Using `competition_list_files` returns an empty file list, however, `competitions_data_list_files` return the correct file list. Using the Kaggle CLI also returns the correct output.
Here is the minimal code to repro the issue:

```
from kaggle.api.kaggle_api_extended import KaggleApi
api = KaggleApi()
api.authenticate()

# Method 1: competition_list_files
method_1 = api.competition_list_files("titanic")
print("Method 1 File List: ", method_1)

# Method 2: competitions_data_list_files
method_2 = api.competitions_data_list_files("titanic")
print("Method 2 File List: ", method_2)
```

Output from above code:
```
Method 1 File List:  
Method 2 File List:  {'files': [{'nameNullable': 'gender_submission.csv', 'descriptionNullable': 'An example of what a submission file should look like. ...
```

Environment Details:
```
kaggle = 1.6.17
python = 3.11.9
```

Please let me know if I missed something or need to add any more details. Thanks!

**Comment by stevemessick** [comment] 2024-07-31 18:57
I think the problem is that `KaggleApi` is not properly initialized. Try following the pattern here:
https://github.com/Kaggle/kaggle-api/blob/main/tests/python_api_tests.py

Let us know if that helps, @deepakn97. Hint: it works when I run it in the debugger (I'm using Rider).

**Comment by stevemessick** [comment] 2024-08-01 19:22
Change
`competition_files = api.competition_list_files("titanic")`
to
`competition_files = api.competition_list_files("titanic")`**`.files`**

`competition_list_files()` returns a `FileList`, which unfortunately does not have a good `__repr__`.

**Comment by stevemessick** [comment] 2024-08-13 22:59
Closing as completed.

**Closed by stevemessick** 2024-08-13 22:59 UTC
Labels: question
