### ISSUE TITLE
Have issue updating pip. Even I used python -m pip install --upgrade pip does not work

### ISSUE THREAD

**Issue by tzec76** [Kaggle/kaggle-api#45] opened 2018-05-21 06:59 UTC
(C:\Users\Jonah Chua\Anaconda3) C:\> pip install kaggle
Collecting kaggle
Exception:
Traceback (most recent call last):
  File "C:\Users\Jonah Chua\Anaconda3\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\Users\Jonah Chua\Anaconda3\lib\site-packages\pip\commands\install.py", line 335, in run
    wb.build(autobuilding=True)
  File "C:\Users\Jonah Chua\Anaconda3\lib\site-packages\pip\wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "C:\Users\Jonah Chua\Anaconda3\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "C:\Users\Jonah Chua\Anaconda3\lib\site-packages\pip\req\req_set.py", line 554, in _prepare_file
    require_hashes
  File "C:\Users\Jonah Chua\Anaconda3\lib\site-packages\pip\req\req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "C:\Users\Jonah Chua\Anaconda3\lib\site-packages\pip\index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "C:\Users\Jonah Chua\Anaconda3\lib\site-packages\pip\index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "C:\Users\Jonah Chua\Anaconda3\lib\site-packages\pip\index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "C:\Users\Jonah Chua\Anaconda3\lib\site-packages\pip\index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "C:\Users\Jonah Chua\Anaconda3\lib\site-packages\pip\index.py", line 811, in get_page
    inst = cls(resp.content, resp.url, resp.headers)
  File "C:\Users\Jonah Chua\Anaconda3\lib\site-packages\pip\index.py", line 731, in __init__
    namespaceHTMLElements=False,
TypeError: parse() got an unexpected keyword argument 'transport_encoding'
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

**Comment by rysteboe** [comment] 2018-05-23 13:19
Try `conda install pip` - https://stackoverflow.com/questions/46499808/pip-throws-typeerror-parse-got-an-unexpected-keyword-argument-transport-enco

**Comment by tzec76** [comment] 2018-05-24 01:48
Hi Rebecca,

It works! I thought I did that already, but, when I clicked, it works.

I try to download data in https://www.kaggle.com/c/singapore-housing-prices/data

Any idea on what is the reason below that I cannot receive the data?

(base) C:\Users\Jonah Chua>kaggle competitions download -c singapore-housing-prices
Traceback (most recent call last):
  File "c:\users\jonah chua\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\jonah chua\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Jonah Chua\Anaconda3\Scripts\kaggle.exe\__main__.py", line 9, in <module>
  File "c:\users\jonah chua\anaconda3\lib\site-packages\kaggle\cli.py", line 46, in main
    out = args.func(**command_args)
  File "c:\users\jonah chua\anaconda3\lib\site-packages\kaggle\api\kaggle_api_extended.py", line 313, in competition_download_cli
    self.competition_download_files(competition, path, force, quiet)
  File "c:\users\jonah chua\anaconda3\lib\site-packages\kaggle\api\kaggle_api_extended.py", line 296, in competition_download_files
    self.competition_download_file(competition, file.ref, path, force, quiet)
  File "c:\users\jonah chua\anaconda3\lib\site-packages\kaggle\api\kaggle_api_extended.py", line 282, in competition_download_file
    id=competition, file_name=file, _preload_content=False))
  File "c:\users\jonah chua\anaconda3\lib\site-packages\kaggle\api\kaggle_api.py", line 147, in competitions_data_download_file_with_http_info
    collection_formats=collection_formats)
  File "c:\users\jonah chua\anaconda3\lib\site-packages\kaggle\api_client.py", line 334, in call_api
    _preload_content, _request_timeout)
  File "c:\users\jonah chua\anaconda3\lib\site-packages\kaggle\api_client.py", line 165, in __call_api
    _request_timeout=_request_timeout)
  File "c:\users\jonah chua\anaconda3\lib\site-packages\kaggle\api_client.py", line 355, in request
    headers=headers)
  File "c:\users\jonah chua\anaconda3\lib\site-packages\kaggle\rest.py", line 251, in GET
    query_params=query_params)
  File "c:\users\jonah chua\anaconda3\lib\site-packages\kaggle\rest.py", line 241, in request
    raise ApiException(http_resp=r)
kaggle.rest.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Cache-Control': 'private', 'Content-Length': '33', 'Content-Type': 'application/json; charset=utf-8', 'X-Kaggle-MillisecondsElapsed': '29', 'X-Kaggle-RequestId': 'a8e83d65a0b6804a5959d984bfaea552', 'X-Kaggle-ApiVersion': '1.3.8', 'Access-Control-Allow-Origin': '*', 'X-Frame-Options': 'SAMEORIGIN', 'Referrer-Policy': 'strict-origin-when-cross-origin', 'Set-Cookie': 'ARRAffinity=7445c6eb4bef0ed725ad31f6d0d880e9f2cd7a8abfac507365805fe959c7203b;Path=/;HttpOnly;Domain=www.kaggle.com', 'Date': 'Thu, 24 May 2018 01:40:50 GMT'})
HTTP response body: b'{"code":404,"message":"NotFound"}'

**Comment by rysteboe** [comment] 2018-05-24 13:53
This is a known bug - see https://github.com/Kaggle/kaggle-api/issues/21.  I'm going to close this out to consolidate issues.  Unfortunately, I don't have an ETA on the bug fix, but it is high priority.

**Comment by rysteboe** [comment] 2018-05-24 13:56
Actually scratch that - that bug focuses more on late competitions and this one could be due to it being an in class competition.  Would have to look into it more to determine if the root cause is the same.  Leaving this open in that case.

**Comment by tzec76** [comment] 2018-05-24 14:26
Thanks Rebecca. It should work. People already are downloading in competition
 :)

**Comment by IzoldaIU** [comment] 2018-11-06 13:46
Hi, I am running Python via Anaconda 3. Every time i try to install kaggle, it gets installed in the following directory: 
c:\users\izolda\new\anaconda3\lib\site_packages

I know I am supposed to put the JSON file in c:\users\izolda.kaggle\kaggle.json, however, when i create that directory and put the json file in it, i still get a syntax error when trying to download a dataset. Wouldn't it make sense to install it where Python will be able to see it? Not sure if I need to re-install anaconda in a different spot. I am very reluctant to make any changes since everything else works perfectly.
Please help! Thanks!

**Comment by rysteboe** [comment] 2018-11-14 14:59
You can use environment variables to specify your token.  Please see the [API credentials](https://github.com/Kaggle/kaggle-api#api-credentials) section of the readme.

**Closed** 2023-06-30 18:27 UTC
