### ISSUE TITLE
Submissions: TypeError: '>=' not supported between instances of 'NoneType' and 'int'

### ISSUE THREAD

**Issue by brentonmallen1** [Kaggle/kaggle-api#108] opened 2018-10-14 00:41 UTC
I made a submission to the `titanic` competition using the API:
`kaggle competitions submissions titanic`
 but when I try to look at my submissions I get the following error:

```
Traceback (most recent call last):
  File "/Users/brentonmallen/miniconda3/envs/titanic/bin/kaggle", line 11, in <module>
    sys.exit(main())
  File "/Users/brentonmallen/miniconda3/envs/titanic/lib/python3.6/site-packages/kaggle/cli.py", line 50, in main
    out = args.func(**command_args)
  File "/Users/brentonmallen/miniconda3/envs/titanic/lib/python3.6/site-packages/kaggle/api/kaggle_api_extended.py", line 536, in competition_submissions_cli
    submissions = self.competition_submissions(competition)
  File "/Users/brentonmallen/miniconda3/envs/titanic/lib/python3.6/site-packages/kaggle/api/kaggle_api_extended.py", line 509, in competition_submissions
    return [Submission(s) for s in submissions_result]
  File "/Users/brentonmallen/miniconda3/envs/titanic/lib/python3.6/site-packages/kaggle/api/kaggle_api_extended.py", line 509, in <listcomp>
    return [Submission(s) for s in submissions_result]
  File "/Users/brentonmallen/miniconda3/envs/titanic/lib/python3.6/site-packages/kaggle/models/kaggle_models_extended.py", line 44, in __init__
    self.size = File.get_size(self.totalBytes)
  File "/Users/brentonmallen/miniconda3/envs/titanic/lib/python3.6/site-packages/kaggle/models/kaggle_models_extended.py", line 94, in get_size
    while size >= 1024 and suffix_index < 4:
TypeError: '>=' not supported between instances of 'NoneType' and 'int'
```

I'm using the attached Conda environment:

```
name: titanic
dependencies:
- pandas=0.23.4
- python=3.6
- pip:
    - zappa==0.46.2
    - flask==1.0.2
    - scikit-learn==0.20
    - cython==0.28.5
    - notebook==5.5.0
    - matplotlib==3.0.0
    - kaggle
```

Any idea what might be causing this?  I wasn't able to find similar issues.

Thanks

**Comment by rysteboe** [comment] 2018-10-15 12:07
I couldn't reproduce this.  What version of the API are you running?  `kaggle -v`

**Comment by brentonmallen1** [comment] 2018-10-15 13:46
I'm running `Kaggle API 1.4.7.1`.  Seems that I am not getting a response when I run the command.  It may have been that it wasn't seeing any of my submissions.

**Comment by rysteboe** [comment] 2018-10-15 14:35
Hmm strange.  Are the submissions appearing correctly on the website?  Are you able to do `kaggle competitions leaderboard titanic --show`?  Just want to see if you're able to request other information from the server.

**Comment by brentonmallen1** [comment] 2018-10-15 14:38
Just noticed a typo in my last message, it should have been `I am now getting a response...`  I am no longer seeing the error.  However, when I was getting the error I was able to see submissions on the submissions page.

I tested the leaderboard command and it seems to work.

**Comment by rysteboe** [comment] 2018-10-15 15:02
If it was a transient issue, I'm going to guess that it was due to some site instability.  I'm going to close this out but also check it against logs/monitoring over the last few days.  Thanks for the report!

**Closed by rysteboe** 2018-10-15 15:02 UTC

**Comment by brentonmallen1** [comment] 2018-10-15 18:08
Thanks for taking the time to look into it.  I might try to make a PR for catching that error, if that's useful.

**Comment by rysteboe** [comment] 2018-10-15 19:33
For these I want to default to the full stack trace I think, since it would be harder to track down with just the error message.

**Comment by 0xb0b** [comment] 2020-05-14 20:09
@rysteboe this bug is still present and can be reproduced. There is #239 open for another case where this bug shows up.
Reproduction:
- make a submission in a code competition
- execute the command to get the submissions list while the submission is in the pending state (code is still executing)
the result is TypeError:

```
(python/fastai)> kaggle competitions submissions abstraction-and-reasoning-challenge
Traceback (most recent call last):
  File "/home/xbob/.env/python/fastai/bin/kaggle", line 11, in <module>
    load_entry_point('kaggle==1.5.6', 'console_scripts', 'kaggle')()
  File "/home/xbob/.env/python/fastai/lib/python3.8/site-packages/kaggle/cli.py", line 51, in main
    out = args.func(**command_args)
  File "/home/xbob/.env/python/fastai/lib/python3.8/site-packages/kaggle/api/kaggle_api_extended.py", line 592, in competition_submissions_cli
    submissions = self.competition_submissions(competition)
  File "/home/xbob/.env/python/fastai/lib/python3.8/site-packages/kaggle/api/kaggle_api_extended.py", line 565, in competition_submissions
    return [Submission(s) for s in submissions_result]
  File "/home/xbob/.env/python/fastai/lib/python3.8/site-packages/kaggle/api/kaggle_api_extended.py", line 565, in <listcomp>
    return [Submission(s) for s in submissions_result]
  File "/home/xbob/.env/python/fastai/lib/python3.8/site-packages/kaggle/models/kaggle_models_extended.py", line 45, in __init__
    self.size = File.get_size(self.totalBytes)
  File "/home/xbob/.env/python/fastai/lib/python3.8/site-packages/kaggle/models/kaggle_models_extended.py", line 107, in get_size
    while size >= 1024 and suffix_index < 4:
TypeError: '>=' not supported between instances of 'NoneType' and 'int'
```
The pull request #240 fixes this issue. With that correction the command works correctly:

```
(python/fastai)> kaggle competitions submissions abstraction-and-reasoning-challenge
fileName          date                 description                     status    publicScore  privateScore  
----------------  -------------------  ------------------------------  --------  -----------  ------------  
kernel4de6a37211  2020-05-14 12:32:55  From Kernel [kernel4de6a37211]  pending   None         None          
kernel4de6a37211  2020-05-14 12:03:52  From Kernel [kernel4de6a37211]  complete  1.000        None          
kernel4de6a37211  2020-05-13 21:11:16  From Kernel [kernel4de6a37211]  complete  1.000        None  
```
