### ISSUE TITLE
Downloading Dataset and getting 403 - Forbidden error in Anaconda Prompt

### ISSUE THREAD

**Issue by Catastrophe9260** [Kaggle/kaggle-api#160] opened 2019-03-02 19:30 UTC
I tried to download the kaggle Diabetic Retinopathy dataset. I installed kaggle API using "pip install", I also have "kaggle.json" with my API credentials.

I get a 403 Forbidden error when using the code sequence "kaggle competitions download -c diabetic-retinopathy-detection" to download the data.

Any thoughts? I need some help.

**Comment by tatianass** [comment] 2019-03-06 01:53
Same here. I looked up at the [dataset](https://www.kaggle.com/c/diabetic-retinopathy-detection/data) and they don't allow it to be downloaded there either.

**Comment by renschler** [comment] 2019-03-06 17:51
you might need to agree to the competitions terms before you can download via api. That's what happened to me.

**Comment by CuriousShoubhik** [comment] 2019-05-14 08:53
Thanks renschler - Once I joined the competition and accepted the terms and conditions I was able to download the data

**Comment by vishal5212** [comment] 2019-09-22 11:12
Thanks renschler. You're right.

**Comment by hemanthyernagula** [comment] 2019-09-29 14:57
Before downloading the kaggle dataset to colab you must accept or join into that competition

**Comment by PanMichael** [comment] 2019-10-17 20:16
1. Go to your kaggle acount and find the dataset you are trying to download 
2. in the data tab, you see API command and download all button
3. click download all button, which will prompt you to the rules tab if you have not accepted terms and conditions 
4. After you accepted terms, go back to data tab where you can either click download all (download a zip file to your HDD) or copy & paste API command to your Colab env.

**Comment by deepaksharma1992** [comment] 2019-11-09 01:55
I have accepted the rules but still not able to download the dataset in Google colabs.
Blindness Detection dataset.

!kaggle datasets download -d c/aptos2019-blindness-detection/

**Comment by Ram04420** [comment] 2020-05-04 10:04
> 1. Go to your kaggle acount and find the dataset you are trying to download
> 2. in the data tab, you see API command and download all button
> 3. click download all button, which will prompt you to the rules tab if you have not accepted terms and conditions
> 4. After you accepted terms, go back to data tab where you can either click download all (download a zip file to your HDD) or copy & paste API command to your Colab env.

**Really thanks to you PanMichael**

**Comment by NARAYANAREDDY37** [comment] 2020-09-18 05:33
> you might need to agree to the competitions terms before you can download via api. That's what happened to me.

Thank you so much!!

**Comment by bfhaha** [comment] 2021-05-04 09:52
Accept it! [https://www.kaggle.com/c/dogs-vs-cats/rules]

**Comment by Password-Classified** [comment] 2021-06-27 15:01
> you might need to agree to the competitions terms before you can download via api. That's what happened to me.

@renschler 

I tried that, but it already says I have accepted the rules, but if I click the **download all** button and it tells me I haven't accepted the rules. Same for downloading the data via the command line api.

**Comment by chAwater** [comment] 2022-05-11 01:45
Duplicate of #87

**Closed** 2023-04-27 05:00 UTC

**Comment by Disservin** [comment] 2024-05-26 12:10
i realized i simply had the wrong name for the dataset.. error was a bit misleading

**Comment by nitinvedwal7111** [comment] 2024-07-15 05:29
> Same here. I looked up at the [dataset](https://www.kaggle.com/c/diabetic-retinopathy-detection/data) and they don't allow it to be downloaded there either.

<img width="696" alt="image" src="https://github.com/user-attachments/assets/b4da7267-ab6c-4215-b4b5-e97c17783ca5">
<img width="695" alt="Screenshot 2024-07-15 105848" src="https://github.com/user-attachments/assets/22ff9cf6-af71-4b1e-851a-d9a92873a52a">
USE COPY API COMMAND

**Comment by fahim202342** [comment] 2025-11-22 13:49
> Same here. I looked up at the [dataset](https://www.kaggle.com/c/diabetic-retinopathy-detection/data) and they don't allow it to be downloaded there either.

i can help you
