### ISSUE TITLE
TypeError: 'NoneType' object is not iterable when updating a dataset

### ISSUE THREAD

**Issue by cyruszhang** [Kaggle/kaggle-api#86] opened 2018-08-28 17:50 UTC
pretty vanilla dataset metadata setup:
`{
  "title": "test_data_set",
  "id": "cyrusea/test_data_set",
  "licenses": [
    {
      "name": "CC0-1.0"
    }
  ]
}`

When I try to update the dataset, it gave me NoneType error on resources, even though resources is optional.
` ~ kaggle datasets version -m "add more data" -p oneplus/`
Traceback (most recent call last):
  File "/anaconda3/bin/kaggle", line 11, in <module>
    sys.exit(main())
  File "/anaconda3/lib/python3.6/site-packages/kaggle/cli.py", line 50, in main
    out = args.func(**command_args)
  File "/anaconda3/lib/python3.6/site-packages/kaggle/api/kaggle_api_extended.py", line 978, in dataset_create_version_cli
    delete_old_versions=delete_old_versions)
  File "/anaconda3/lib/python3.6/site-packages/kaggle/api/kaggle_api_extended.py", line 930, in dataset_create_version
    self.validate_resources(folder, resources)
  File "/anaconda3/lib/python3.6/site-packages/kaggle/api/kaggle_api_extended.py", line 1831, in validate_resources
    self.validate_files_exist(folder, resources)
  File "/anaconda3/lib/python3.6/site-packages/kaggle/api/kaggle_api_extended.py", line 1835, in validate_files_exist
    for item in resources:
TypeError: 'NoneType' object is not iterable

Kaggle version: 1.4.6

**Comment by rysteboe** [comment] 2018-08-28 19:07
Dupe of #77 

Fix will be out soon.

**Closed by rysteboe** 2018-08-28 19:07 UTC
